name: My tester
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run my specifics
        id: specs
        uses: neal-core/custom-action@main
        with:
          username: Neal
      - name: Run the output
        run: echo "Returned ${{steps.specs.outputs.greeting}}"
